version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: bababos-db
    restart: always
    environment:
      POSTGRES_USER: fathur
      POSTGRES_PASSWORD: plokijuh
      POSTGRES_DB: bababos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: