# Generated by Django 5.0.2 on 2024-02-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, editable=False, null=True
            ),
        ),
    ]
