# Generated by Django 5.0.2 on 2024-03-03 04:20

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0002_supplier_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_prices",
                to="pricing.product",
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=100)),
                ("chosen_price", models.DecimalField(decimal_places=5, max_digits=21)),
                ("final_price", models.DecimalField(decimal_places=5, max_digits=21)),
                ("profit_margin", models.DecimalField(decimal_places=5, max_digits=8)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="pricing.rfq",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pricing.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
            },
        ),
    ]
