# Generated by Django 5.0.2 on 2024-03-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0003_alter_supplierprice_product_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierprice",
            name="latest",
            field=models.BooleanField(default=True),
        ),
    ]
