# Generated by Django 5.0.2 on 2024-03-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0005_remove_transaction_supplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
