# Generated by Django 5.0.2 on 2024-03-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0007_alter_transaction_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="profit_margin",
            new_name="analyzed_profit_margin",
        ),
    ]
